
version: '3.8'


services:
  
  backend:
  
    build: ./backend
    ports:
    
      - "3000:3000"
    environment:
   
      - DB_HOST=db        
      - DB_USER=guestbook_user
      - DB_PASSWORD=secret
      - DB_NAME=guestbook
    depends_on:
     
      - db


  db:
    
    image: mysql:8.0
  
    cap_add:
      - SYS_NICE
 
    restart: always
    environment:
   
      - MYSQL_DATABASE=guestbook
      - MYSQL_USER=guestbook_user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      
      - "3306:3306"
    volumes:
     .
      - db-data:/var/lib/mysql


volumes:
  db-data: